version: '3.1'

services:

  db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080